version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "shutter2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xrgtl9dspann"
s3_prefix = "shutter2"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
